# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "talos-systems/sidero"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.4.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.capi]
        title = "CAPI v1beta1"
        description = """\
This release of CACPPT brings compatibility with CAPI v1beta1.
"""

    [notes.ipmi-pxe-method]
        title = "IPMI PXE Method"
        description = """\
IPMI PXE method (UEFI, BIOS) can now be configured with `SIDERO_CONTROLLER_MANAGER_IPMI_PXE_METHOD` while installing Sidero.
"""

    [notes.siderolink]
        title = "Siderolink"
        description = """\
Sidero now connects to all servers using Siderolink.
This enables streaming of all dmesg logs and events back to sidero.

All server logs can now be viewed by getting logs of one of the container of the `sidero-controller-manager`:

```
kubectl logs -f -n sidero-system deployment/sidero-controller-manager serverlogs
```

Events:

```
kubectl logs -f -n sidero-system deployment/sidero-controller-manager serverevents
```
"""

    [notes.addresses]
        title = "Machine Addresses"
        description = """\
Sidero now populates `MetalMachine` addresses with the ones discovered from Siderolink server events.
Which is then propagated to CAPI `Machine` resources.

Requires Talos >= v0.14.
"""

    [notes.conditions]
        title = "New `MetalMachines` Conditions"
        description = """\
New set of conditions is now available which can simplify cluster troubleshooting:

- `TalosConfigLoaded` is set to false when the config load has failed.
- `TalosConfigValidated` is set to false when the config validation
fails on the node.
- `TalosInstalled` is set to true/false when talos installer finishes.
"""

    [notes.pxeboot]
        title = "Retry PXE Boot"
        description = """\
Sidero server controller now keeps track of Talos installation progress.
Now the node will be PXE booted until Talos installation succeeds.
"""
