# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "talos-systems/sidero"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.5.0"

pre_release = false

preface = """\
"""

[notes]

    [notes.config]
        title = "Sidero Deployment Strategy Configuration"
        description = """\
Allow configuring deployment strategy. Setting the deployment strategy to `Recreate` when running a single instance of Sidero
makes it possible to upgrade the pod (but with a small amount of downtime).
""" 
